/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pawnandplay.view;
import com.pawnandplay.util.ValidationUtil;
import com.pawnandplay.model.gamesModel;
import java.util.List;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sanskritia
 */
public class boardGames extends javax.swing.JFrame {
    
    private List<gamesModel> gamesList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color yellowColor = new Color(239, 192, 32);
    
    /**
     * Creates new form boardGames
     */
    public boardGames() {
        initComponents();
        validationUtil = new ValidationUtil();
        initializeLayout();
        initializeData(); 
        startProgress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginScreen = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        gif = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        loginerror = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        mainHeader = new javax.swing.JPanel();
        headertext1 = new javax.swing.JLabel();
        headertext2 = new javax.swing.JLabel();
        mainpawnimg = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JPanel();
        hHomebtn = new javax.swing.JButton();
        hProdbtn = new javax.swing.JButton();
        hCartbtn = new javax.swing.JButton();
        homeheaderimg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        homeimg = new javax.swing.JLabel();
        productPage = new javax.swing.JPanel();
        productHeader = new javax.swing.JPanel();
        headertext3 = new javax.swing.JLabel();
        headertext4 = new javax.swing.JLabel();
        mainpawnimg1 = new javax.swing.JLabel();
        productMenuBar = new javax.swing.JPanel();
        pHomebtn = new javax.swing.JButton();
        pProdbtn = new javax.swing.JButton();
        pEntrybtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameTable = new javax.swing.JTable();
        prodimg = new javax.swing.JLabel();
        entryPage = new javax.swing.JPanel();
        cartHeader = new javax.swing.JPanel();
        headertext5 = new javax.swing.JLabel();
        headertext6 = new javax.swing.JLabel();
        mainpawnimg2 = new javax.swing.JLabel();
        cartMenuBar = new javax.swing.JPanel();
        cHomebtn = new javax.swing.JButton();
        cProdbtn = new javax.swing.JButton();
        cCartbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        carttxtarea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        orderlabel = new javax.swing.JLabel();
        cprodIDLabel = new javax.swing.JLabel();
        cquantityLabel = new javax.swing.JLabel();
        cpfield = new javax.swing.JTextField();
        cqfield = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        loadingScreen = new javax.swing.JPanel();
        pawnandplay = new javax.swing.JLabel();
        loadingtag = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        loadingimg2 = new javax.swing.JLabel();
        loadingimg1 = new javax.swing.JLabel();

        loginScreen.setBackground(new java.awt.Color(128, 74, 74));
        loginScreen.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 48)); // NOI18N
        loginScreen.setPreferredSize(new java.awt.Dimension(1512, 958));

        welcomeLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("WELCOME BACK!");
        welcomeLabel.setLocation(new java.awt.Point(1031, 278));
        welcomeLabel.setMaximumSize(new java.awt.Dimension(416, 66));
        welcomeLabel.setMinimumSize(new java.awt.Dimension(416, 66));
        welcomeLabel.setPreferredSize(new java.awt.Dimension(416, 66));
        welcomeLabel.setSize(new java.awt.Dimension(416, 66));

        usernameLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 24)); // NOI18N
        usernameLabel.setText("USERNAME:");

        passwordLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 24)); // NOI18N
        passwordLabel.setText("PASSWORD:");

        usernameField.setBackground(new java.awt.Color(239, 183, 183));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/logingif.gif"))); // NOI18N

        loginBtn.setBackground(new java.awt.Color(239, 183, 183));
        loginBtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginerror.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        loginerror.setForeground(new java.awt.Color(204, 0, 0));

        passwordField.setBackground(new java.awt.Color(239, 183, 183));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 36)); // NOI18N
        loginLabel.setText("UNLEASH FUN, ONE GAME AT A TIME");

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addGap(426, 426, 426))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(37, 37, 37)
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(usernameLabel))
                .addGap(145, 145, 145))
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField)))
                    .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(loginLabel)
                .addGap(24, 24, 24))
        );

        homePage.setBackground(new java.awt.Color(128, 74, 74));
        homePage.setMaximumSize(new java.awt.Dimension(1512, 982));
        homePage.setMinimumSize(new java.awt.Dimension(1512, 982));
        homePage.setSize(new java.awt.Dimension(1512, 982));

        mainHeader.setBackground(new java.awt.Color(194, 117, 117));
        mainHeader.setBounds(new java.awt.Rectangle(0, 0, 1512, 102));
        mainHeader.setMaximumSize(new java.awt.Dimension(1512, 102));

        headertext1.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext1.setText("GAME ON - THE FUN NEVER ENDS");

        headertext2.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext2.setForeground(new java.awt.Color(255, 255, 255));
        headertext2.setText("PAWN AND PLAY");

        mainpawnimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/head.png"))); // NOI18N

        javax.swing.GroupLayout mainHeaderLayout = new javax.swing.GroupLayout(mainHeader);
        mainHeader.setLayout(mainHeaderLayout);
        mainHeaderLayout.setHorizontalGroup(
            mainHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headertext1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headertext2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpawnimg)
                .addGap(135, 135, 135))
        );
        mainHeaderLayout.setVerticalGroup(
            mainHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(headertext1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headertext2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addComponent(mainpawnimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        mainMenuBar.setBackground(new java.awt.Color(239, 183, 183));
        mainMenuBar.setBounds(new java.awt.Rectangle(0, 102, 1512, 61));
        mainMenuBar.setMaximumSize(new java.awt.Dimension(1512, 61));

        hHomebtn.setBackground(new java.awt.Color(239, 183, 183));
        hHomebtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        hHomebtn.setText("Home");
        hHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hHomebtnActionPerformed(evt);
            }
        });

        hProdbtn.setBackground(new java.awt.Color(239, 183, 183));
        hProdbtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        hProdbtn.setText("Product");
        hProdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hProdbtnActionPerformed(evt);
            }
        });

        hCartbtn.setBackground(new java.awt.Color(239, 183, 183));
        hCartbtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        hCartbtn.setText("Entry");
        hCartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hCartbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuBarLayout = new javax.swing.GroupLayout(mainMenuBar);
        mainMenuBar.setLayout(mainMenuBarLayout);
        mainMenuBarLayout.setHorizontalGroup(
            mainMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuBarLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(hHomebtn)
                .addGap(308, 308, 308)
                .addComponent(hProdbtn)
                .addGap(308, 308, 308)
                .addComponent(hCartbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(homeheaderimg)
                .addGap(111, 111, 111))
        );
        mainMenuBarLayout.setVerticalGroup(
            mainMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuBarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(homeheaderimg)
                .addGap(0, 0, 0)
                .addGroup(mainMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hHomebtn)
                    .addComponent(hProdbtn)
                    .addComponent(hCartbtn))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jTextArea1.setBackground(new java.awt.Color(128, 74, 74));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("                                          Welcome to Pawn & Play –\n                                 Your Ultimate Board Game Destination!\n\n   At Pawn & Play, we believe that life’s best moments happen around a game board. \n   Whether you’re a seasoned strategist, a casual player, or someone just discovering\n   the joy of board gaming, we have something for everyone. From timeless classics to \n   the latest adventures, our collection spans a world of fun, strategy, and unforgettable\n   memories.\n\n\n   Explore our carefully curated selection of family games, party hits, strategic epics,\n   and everything in between. With our passion for play and commitment to quality, \n   we aim to bring people together one game at a time.\n\n\n            Your next great gaming experience starts here. Ready to roll the dice?");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        homeimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/home.jpeg"))); // NOI18N

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(homeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePageLayout.createSequentialGroup()
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 451, Short.MAX_VALUE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 661, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        productPage.setBackground(new java.awt.Color(128, 74, 74));
        productPage.setMaximumSize(new java.awt.Dimension(1512, 982));
        productPage.setMinimumSize(new java.awt.Dimension(1512, 982));
        productPage.setSize(new java.awt.Dimension(1512, 982));

        productHeader.setBackground(new java.awt.Color(194, 117, 117));
        productHeader.setBounds(new java.awt.Rectangle(0, 0, 1512, 102));
        productHeader.setMaximumSize(new java.awt.Dimension(1512, 102));

        headertext3.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext3.setText("GAME ON - THE FUN NEVER ENDS");

        headertext4.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext4.setForeground(new java.awt.Color(255, 255, 255));
        headertext4.setText("PAWN AND PLAY");

        mainpawnimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/head.png"))); // NOI18N

        javax.swing.GroupLayout productHeaderLayout = new javax.swing.GroupLayout(productHeader);
        productHeader.setLayout(productHeaderLayout);
        productHeaderLayout.setHorizontalGroup(
            productHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(productHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headertext3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headertext4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1018, Short.MAX_VALUE)
                .addComponent(mainpawnimg1)
                .addGap(366, 366, 366))
        );
        productHeaderLayout.setVerticalGroup(
            productHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productHeaderLayout.createSequentialGroup()
                .addGroup(productHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainpawnimg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productHeaderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(headertext3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headertext4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        productMenuBar.setBackground(new java.awt.Color(239, 183, 183));
        productMenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        productMenuBar.setBounds(new java.awt.Rectangle(0, 102, 1512, 61));
        productMenuBar.setMaximumSize(new java.awt.Dimension(1512, 61));

        pHomebtn.setBackground(new java.awt.Color(239, 183, 183));
        pHomebtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        pHomebtn.setText("Home");
        pHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pHomebtnActionPerformed(evt);
            }
        });

        pProdbtn.setBackground(new java.awt.Color(239, 183, 183));
        pProdbtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        pProdbtn.setText("Product");
        pProdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pProdbtnActionPerformed(evt);
            }
        });

        pEntrybtn.setBackground(new java.awt.Color(239, 183, 183));
        pEntrybtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        pEntrybtn.setText("Entry");
        pEntrybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEntrybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productMenuBarLayout = new javax.swing.GroupLayout(productMenuBar);
        productMenuBar.setLayout(productMenuBarLayout);
        productMenuBarLayout.setHorizontalGroup(
            productMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productMenuBarLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(pHomebtn)
                .addGap(353, 353, 353)
                .addComponent(pProdbtn)
                .addGap(394, 394, 394)
                .addComponent(pEntrybtn)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        productMenuBarLayout.setVerticalGroup(
            productMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productMenuBarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(productMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pHomebtn)
                    .addComponent(pProdbtn)
                    .addComponent(pEntrybtn))
                .addGap(21, 21, 21))
        );

        gameTable.setBackground(new java.awt.Color(239, 183, 183));
        gameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Level", "Genre", "Age", "Stock", "Price"
            }
        ));
        jScrollPane2.setViewportView(gameTable);

        prodimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/product.png"))); // NOI18N

        javax.swing.GroupLayout productPageLayout = new javax.swing.GroupLayout(productPage);
        productPage.setLayout(productPageLayout);
        productPageLayout.setHorizontalGroup(
            productPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPageLayout.createSequentialGroup()
                .addGroup(productPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(productPageLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(prodimg, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productPageLayout.setVerticalGroup(
            productPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPageLayout.createSequentialGroup()
                .addComponent(productHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(productPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productPageLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPageLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(prodimg)))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        entryPage.setBackground(new java.awt.Color(128, 74, 74));
        entryPage.setForeground(new java.awt.Color(255, 255, 255));
        entryPage.setMaximumSize(new java.awt.Dimension(1512, 982));
        entryPage.setMinimumSize(new java.awt.Dimension(1512, 982));
        entryPage.setSize(new java.awt.Dimension(1512, 982));

        cartHeader.setBackground(new java.awt.Color(194, 117, 117));
        cartHeader.setBounds(new java.awt.Rectangle(0, 0, 1512, 102));
        cartHeader.setMaximumSize(new java.awt.Dimension(1512, 102));

        headertext5.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext5.setText("GAME ON - THE FUN NEVER ENDS");

        headertext6.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        headertext6.setForeground(new java.awt.Color(255, 255, 255));
        headertext6.setText("PAWN AND PLAY");

        mainpawnimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/head.png"))); // NOI18N

        javax.swing.GroupLayout cartHeaderLayout = new javax.swing.GroupLayout(cartHeader);
        cartHeader.setLayout(cartHeaderLayout);
        cartHeaderLayout.setHorizontalGroup(
            cartHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(cartHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headertext5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headertext6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpawnimg2)
                .addGap(87, 87, 87))
        );
        cartHeaderLayout.setVerticalGroup(
            cartHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(headertext5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headertext6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(cartHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainpawnimg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cartMenuBar.setBackground(new java.awt.Color(239, 183, 183));
        cartMenuBar.setBounds(new java.awt.Rectangle(0, 102, 1512, 61));
        cartMenuBar.setMaximumSize(new java.awt.Dimension(1512, 61));

        cHomebtn.setBackground(new java.awt.Color(239, 183, 183));
        cHomebtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        cHomebtn.setText("Home");

        cProdbtn.setBackground(new java.awt.Color(239, 183, 183));
        cProdbtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        cProdbtn.setText("Product");
        cProdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProdbtnActionPerformed(evt);
            }
        });

        cCartbtn.setBackground(new java.awt.Color(239, 183, 183));
        cCartbtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        cCartbtn.setText("Entry");

        javax.swing.GroupLayout cartMenuBarLayout = new javax.swing.GroupLayout(cartMenuBar);
        cartMenuBar.setLayout(cartMenuBarLayout);
        cartMenuBarLayout.setHorizontalGroup(
            cartMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartMenuBarLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(cHomebtn)
                .addGap(308, 308, 308)
                .addComponent(cProdbtn)
                .addGap(308, 308, 308)
                .addComponent(cCartbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartMenuBarLayout.setVerticalGroup(
            cartMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartMenuBarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(cartMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cHomebtn)
                    .addComponent(cProdbtn)
                    .addComponent(cCartbtn))
                .addGap(19, 19, 19))
        );

        carttxtarea.setBackground(new java.awt.Color(128, 74, 74));
        carttxtarea.setColumns(20);
        carttxtarea.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        carttxtarea.setForeground(new java.awt.Color(255, 255, 255));
        carttxtarea.setRows(5);
        carttxtarea.setText("                     Your adventure into the world of board games is just around the corner! \n                Whether you’re planning an epic strategy night, a family-friendly competition, \n                       or a cozy puzzle session, your cart is filled with fun waiting to happen.\n\n          Board games aren’t just games—they’re stories, challenges, and unforgettable memories.\n        Take a moment to double-check your selections, and get ready to roll the dice, shuffle the \n                                                    cards, or conquer the board.");
        carttxtarea.setBorder(null);
        jScrollPane3.setViewportView(carttxtarea);

        cartTable.setBackground(new java.awt.Color(239, 183, 183));
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Quantity", "Price"
            }
        ));
        jScrollPane4.setViewportView(cartTable);

        orderlabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 36)); // NOI18N
        orderlabel.setText("Is your order correct?");

        cprodIDLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        cprodIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        cprodIDLabel.setText("Product ID");

        cquantityLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        cquantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cquantityLabel.setText("Quantity");

        deletebtn.setBackground(new java.awt.Color(239, 183, 183));
        deletebtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        deletebtn.setText("DELETE");

        updatebtn.setBackground(new java.awt.Color(239, 183, 183));
        updatebtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 18)); // NOI18N
        updatebtn.setText("UPDATE");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/cart2.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/cart1.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(239, 183, 183));
        jButton1.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(239, 183, 183));
        jButton2.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        jButton2.setText("UPDATE");

        jButton3.setBackground(new java.awt.Color(239, 183, 183));
        jButton3.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        jButton3.setText("DELETE");

        jPanel1.setBackground(new java.awt.Color(239, 183, 183));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel4.setText("Product Name");

        jLabel5.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel5.setText("Level");

        jLabel6.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel6.setText("Genre");

        jLabel7.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel8.setText("Stock");

        jLabel9.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel9.setText("Price");

        jLabel10.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 15)); // NOI18N
        jLabel10.setText("Brand");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout entryPageLayout = new javax.swing.GroupLayout(entryPage);
        entryPage.setLayout(entryPageLayout);
        entryPageLayout.setHorizontalGroup(
            entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cartMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
            .addGroup(entryPageLayout.createSequentialGroup()
                .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(entryPageLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(entryPageLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(orderlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(entryPageLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deletebtn)
                                            .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cquantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cprodIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                                        .addGap(39, 39, 39)
                                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, entryPageLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(updatebtn))
                                            .addComponent(cpfield, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                            .addComponent(cqfield))))))))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        entryPageLayout.setVerticalGroup(
            entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPageLayout.createSequentialGroup()
                .addComponent(cartHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cartMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(entryPageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(entryPageLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton1)
                                .addGap(80, 80, 80)
                                .addComponent(jButton2)
                                .addGap(80, 80, 80)
                                .addComponent(jButton3)))))
                .addGap(736, 736, 736)
                .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entryPageLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(orderlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cprodIDLabel)
                            .addComponent(cpfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cqfield)
                            .addComponent(cquantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(128, 128, 128)
                        .addGroup(entryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletebtn)
                            .addComponent(updatebtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadingScreen.setBackground(new java.awt.Color(128, 74, 74));
        loadingScreen.setPreferredSize(new java.awt.Dimension(1512, 958));
        loadingScreen.setSize(new java.awt.Dimension(1512, 958));

        pawnandplay.setBackground(new java.awt.Color(0, 0, 0));
        pawnandplay.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 48)); // NOI18N
        pawnandplay.setForeground(new java.awt.Color(255, 255, 255));
        pawnandplay.setText("PAWN AND PLAY");
        pawnandplay.setAlignmentX(652.0F);
        pawnandplay.setAlignmentY(326.0F);
        pawnandplay.setBounds(new java.awt.Rectangle(652, 326, 0, 0));
        pawnandplay.setMaximumSize(new java.awt.Dimension(441, 73));
        pawnandplay.setMinimumSize(new java.awt.Dimension(441, 73));

        loadingtag.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 40)); // NOI18N
        loadingtag.setText("YOUR NEXT FAVOURITE GAME IS WAITING");
        loadingtag.setLocation(new java.awt.Point(313, 350));
        loadingtag.setMaximumSize(new java.awt.Dimension(888, 57));
        loadingtag.setMinimumSize(new java.awt.Dimension(888, 57));

        progress.setBackground(new java.awt.Color(239, 183, 183));
        progress.setForeground(new java.awt.Color(239, 183, 183));
        progress.setBounds(new java.awt.Rectangle(565, 714, 384, 35));
        progress.setMaximumSize(new java.awt.Dimension(384, 35));
        progress.setMinimumSize(new java.awt.Dimension(384, 35));
        progress.setPreferredSize(new java.awt.Dimension(384, 35));

        loading.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 36)); // NOI18N
        loading.setText("Loading ...");
        loading.setLocation(new java.awt.Point(170, 54));
        loading.setPreferredSize(new java.awt.Dimension(170, 54));

        loadingimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/loading2.png"))); // NOI18N

        loadingimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pawnandplay/resources/loading1.png"))); // NOI18N

        javax.swing.GroupLayout loadingScreenLayout = new javax.swing.GroupLayout(loadingScreen);
        loadingScreen.setLayout(loadingScreenLayout);
        loadingScreenLayout.setHorizontalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingScreenLayout.createSequentialGroup()
                .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addContainerGap(396, Short.MAX_VALUE)
                        .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loadingtag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pawnandplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(loadingimg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadingimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loadingScreenLayout.setVerticalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadingimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingScreenLayout.createSequentialGroup()
                .addGap(0, 778, Short.MAX_VALUE)
                .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingScreenLayout.createSequentialGroup()
                        .addComponent(pawnandplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadingtag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingScreenLayout.createSequentialGroup()
                        .addComponent(loadingimg1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loadingScreen, "LoadingScreen");
        getContentPane().add(loginScreen, "LoginScreen");
        getContentPane().add(homePage, "MainScreen");
        getContentPane().add(productPage, "ProductScreen");
        getContentPane().add(entryPage, "EntryScreen");
        
        // Start with the loading screen
        loadScreen("loadingScreen");
    }
    
    private void initializeData() {
        gamesList = new LinkedList<>();
       
    //registering sample data 
    }
    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int prog = chunks.get(chunks.size() - 1);
                progress.setValue(prog);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    
    // Method to add student data and populate the table
    
    private void registerGame (gamesModel games) {
        gamesList.add(games);
        DefaultTableModel model = (DefaultTableModel) gameTable.getModel();
        model.addRow(new Object[]{
            games.getID(), games.getProductname(), games.getLevel(),
            games.getGenre(), games.getAge(), games.getStock(), games.getPrice()
        });
    } 

    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    
    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:                                        
        // Get the username and password input
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            loginerror.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            loginerror.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            loginerror.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void hProdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hProdbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hProdbtnActionPerformed

    private void pProdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pProdbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pProdbtnActionPerformed

    private void cProdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProdbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cProdbtnActionPerformed

    private void hHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hHomebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hHomebtnActionPerformed

    private void hCartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hCartbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hCartbtnActionPerformed

    private void pHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pHomebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pHomebtnActionPerformed

    private void pEntrybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEntrybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pEntrybtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boardGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boardGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boardGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boardGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boardGames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cCartbtn;
    private javax.swing.JButton cHomebtn;
    private javax.swing.JButton cProdbtn;
    private javax.swing.JPanel cartHeader;
    private javax.swing.JPanel cartMenuBar;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextArea carttxtarea;
    private javax.swing.JTextField cpfield;
    private javax.swing.JLabel cprodIDLabel;
    private javax.swing.JTextField cqfield;
    private javax.swing.JLabel cquantityLabel;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel entryPage;
    private javax.swing.JTable gameTable;
    private javax.swing.JLabel gif;
    private javax.swing.JButton hCartbtn;
    private javax.swing.JButton hHomebtn;
    private javax.swing.JButton hProdbtn;
    private javax.swing.JLabel headertext1;
    private javax.swing.JLabel headertext2;
    private javax.swing.JLabel headertext3;
    private javax.swing.JLabel headertext4;
    private javax.swing.JLabel headertext5;
    private javax.swing.JLabel headertext6;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homeheaderimg;
    private javax.swing.JLabel homeimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel loading;
    private javax.swing.JPanel loadingScreen;
    private javax.swing.JLabel loadingimg1;
    private javax.swing.JLabel loadingimg2;
    private javax.swing.JLabel loadingtag;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JLabel loginerror;
    private javax.swing.JPanel mainHeader;
    private javax.swing.JPanel mainMenuBar;
    private javax.swing.JLabel mainpawnimg;
    private javax.swing.JLabel mainpawnimg1;
    private javax.swing.JLabel mainpawnimg2;
    private javax.swing.JLabel orderlabel;
    private javax.swing.JButton pEntrybtn;
    private javax.swing.JButton pHomebtn;
    private javax.swing.JButton pProdbtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pawnandplay;
    private javax.swing.JLabel prodimg;
    private javax.swing.JPanel productHeader;
    private javax.swing.JPanel productMenuBar;
    private javax.swing.JPanel productPage;
    private javax.swing.JProgressBar progress;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
